use lazy_static::lazy_static;
use std::collections::HashMap;
use super::addressing::*;
use super::addressing::OperandType::*;
use super::addressing::ConditionOperand::*;
use super::addressing::RegisterOperand::*;
use super::addressing::LiteralOperand::*;

fn vec_to_map(v: Vec<Opcode>) -> HashMap<u8, Opcode> {
  let mut map = HashMap::new();
  for item in v { map.insert(item.code, item); }

  map
}

lazy_static! {
  pub static ref OPTABLE: HashMap<u8, Opcode> = {
    let opcodes = vec![
      Opcode {code: 0x00, name: "NOP", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0x01, name: "LD", bytes: 3, cycles: 12, immediate: true, operands: vec!(Operand {kind: Register(BC), immediate: true}, Operand {kind: Literal(n16), immediate: true})}, 
      Opcode {code: 0x02, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(BC), immediate: false}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x03, name: "INC", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(BC), immediate: true})}, 
      Opcode {code: 0x04, name: "INC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x05, name: "DEC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x06, name: "LD", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0x07, name: "RLCA", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0x08, name: "LD", bytes: 3, cycles: 20, immediate: false, operands: vec!(Operand {kind: Literal(a16), immediate: false}, Operand {kind: Register(SP), immediate: true})}, 
      Opcode {code: 0x09, name: "ADD", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true}, Operand {kind: Register(BC), immediate: true})}, 
      Opcode {code: 0x0A, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(BC), immediate: false})}, 
      Opcode {code: 0x0B, name: "DEC", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(BC), immediate: true})}, 
      Opcode {code: 0x0C, name: "INC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x0D, name: "DEC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x0E, name: "LD", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0x0F, name: "RRCA", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0x10, name: "STOP", bytes: 2, cycles: 4, immediate: true, operands: vec!(Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0x11, name: "LD", bytes: 3, cycles: 12, immediate: true, operands: vec!(Operand {kind: Register(DE), immediate: true}, Operand {kind: Literal(n16), immediate: true})}, 
      Opcode {code: 0x12, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(DE), immediate: false}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x13, name: "INC", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(DE), immediate: true})}, 
      Opcode {code: 0x14, name: "INC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x15, name: "DEC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x16, name: "LD", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0x17, name: "RLA", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0x18, name: "JR", bytes: 2, cycles: 12, immediate: true, operands: vec!(Operand {kind: Literal(e8), immediate: true})}, 
      Opcode {code: 0x19, name: "ADD", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true}, Operand {kind: Register(DE), immediate: true})}, 
      Opcode {code: 0x1A, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(DE), immediate: false})}, 
      Opcode {code: 0x1B, name: "DEC", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(DE), immediate: true})}, 
      Opcode {code: 0x1C, name: "INC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x1D, name: "DEC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x1E, name: "LD", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0x1F, name: "RRA", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0x20, name: "JR", bytes: 2, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(NZ), immediate: true}, Operand {kind: Literal(e8), immediate: true})}, 
      Opcode {code: 0x21, name: "LD", bytes: 3, cycles: 12, immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true}, Operand {kind: Literal(n16), immediate: true})}, 
      Opcode {code: 0x22, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x23, name: "INC", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true})}, 
      Opcode {code: 0x24, name: "INC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x25, name: "DEC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x26, name: "LD", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0x27, name: "DAA", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0x28, name: "JR", bytes: 2, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(Z), immediate: true}, Operand {kind: Literal(e8), immediate: true})}, 
      Opcode {code: 0x29, name: "ADD", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true}, Operand {kind: Register(HL), immediate: true})}, 
      Opcode {code: 0x2A, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x2B, name: "DEC", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true})}, 
      Opcode {code: 0x2C, name: "INC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x2D, name: "DEC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x2E, name: "LD", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0x2F, name: "CPL", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0x30, name: "JR", bytes: 2, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(NC), immediate: true}, Operand {kind: Literal(e8), immediate: true})}, 
      Opcode {code: 0x31, name: "LD", bytes: 3, cycles: 12, immediate: true, operands: vec!(Operand {kind: Register(SP), immediate: true}, Operand {kind: Literal(n16), immediate: true})}, 
      Opcode {code: 0x32, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x33, name: "INC", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(SP), immediate: true})}, 
      Opcode {code: 0x34, name: "INC", bytes: 1, cycles: 12, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x35, name: "DEC", bytes: 1, cycles: 12, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x36, name: "LD", bytes: 2, cycles: 12, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0x37, name: "SCF", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0x38, name: "JR", bytes: 2, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(CY), immediate: true}, Operand {kind: Literal(e8), immediate: true})}, 
      Opcode {code: 0x39, name: "ADD", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true}, Operand {kind: Register(SP), immediate: true})}, 
      Opcode {code: 0x3A, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x3B, name: "DEC", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(SP), immediate: true})}, 
      Opcode {code: 0x3C, name: "INC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x3D, name: "DEC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x3E, name: "LD", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0x3F, name: "CCF", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0x40, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x41, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x42, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x43, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x44, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x45, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x46, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x47, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x48, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x49, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x4A, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x4B, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x4C, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x4D, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x4E, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x4F, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x50, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x51, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x52, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x53, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x54, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x55, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x56, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x57, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x58, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x59, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x5A, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x5B, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x5C, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x5D, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x5E, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x5F, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x60, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x61, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x62, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x63, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x64, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x65, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x66, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x67, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x68, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x69, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x6A, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x6B, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x6C, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x6D, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x6E, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x6F, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x70, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x71, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x72, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x73, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x74, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x75, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x76, name: "HALT", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0x77, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x78, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x79, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x7A, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x7B, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x7C, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x7D, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x7E, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x7F, name: "LD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x80, name: "ADD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x81, name: "ADD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x82, name: "ADD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x83, name: "ADD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x84, name: "ADD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x85, name: "ADD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x86, name: "ADD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x87, name: "ADD", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x88, name: "ADC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x89, name: "ADC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x8A, name: "ADC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x8B, name: "ADC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x8C, name: "ADC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x8D, name: "ADC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x8E, name: "ADC", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x8F, name: "ADC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x90, name: "SUB", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x91, name: "SUB", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x92, name: "SUB", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x93, name: "SUB", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x94, name: "SUB", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x95, name: "SUB", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x96, name: "SUB", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x97, name: "SUB", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x98, name: "SBC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x99, name: "SBC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x9A, name: "SBC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x9B, name: "SBC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x9C, name: "SBC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x9D, name: "SBC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x9E, name: "SBC", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x9F, name: "SBC", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xA0, name: "AND", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xA1, name: "AND", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xA2, name: "AND", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xA3, name: "AND", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xA4, name: "AND", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xA5, name: "AND", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xA6, name: "AND", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xA7, name: "AND", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xA8, name: "XOR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xA9, name: "XOR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xAA, name: "XOR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xAB, name: "XOR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xAC, name: "XOR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xAD, name: "XOR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xAE, name: "XOR", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xAF, name: "XOR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xB0, name: "OR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xB1, name: "OR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xB2, name: "OR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xB3, name: "OR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xB4, name: "OR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xB5, name: "OR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xB6, name: "OR", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xB7, name: "OR", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xB8, name: "CP", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xB9, name: "CP", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xBA, name: "CP", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xBB, name: "CP", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xBC, name: "CP", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xBD, name: "CP", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xBE, name: "CP", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xBF, name: "CP", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xC0, name: "RET", bytes: 1, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(NZ), immediate: true})}, 
      Opcode {code: 0xC1, name: "POP", bytes: 1, cycles: 12, immediate: true, operands: vec!(Operand {kind: Register(BC), immediate: true})}, 
      Opcode {code: 0xC2, name: "JP", bytes: 3, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(NZ), immediate: true}, Operand {kind: Literal(a16), immediate: true})}, 
      Opcode {code: 0xC3, name: "JP", bytes: 3, cycles: 16, immediate: true, operands: vec!(Operand {kind: Literal(a16), immediate: true})}, 
      Opcode {code: 0xC4, name: "CALL", bytes: 3, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(NZ), immediate: true}, Operand {kind: Literal(a16), immediate: true})}, 
      Opcode {code: 0xC5, name: "PUSH", bytes: 1, cycles: 16, immediate: true, operands: vec!(Operand {kind: Register(BC), immediate: true})}, 
      Opcode {code: 0xC6, name: "ADD", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0xC7, name: "RST", bytes: 1, cycles: 16, immediate: true, operands: vec!(Operand {kind: Interrupt(0x00), immediate: true})}, 
      Opcode {code: 0xC8, name: "RET", bytes: 1, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(Z), immediate: true})}, 
      Opcode {code: 0xC9, name: "RET", bytes: 1, cycles: 16, immediate: true, operands: vec!()}, 
      Opcode {code: 0xCA, name: "JP", bytes: 3, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(Z), immediate: true}, Operand {kind: Literal(a16), immediate: true})}, 
      Opcode {code: 0xCB, name: "PREFIX", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xCC, name: "CALL", bytes: 3, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(Z), immediate: true}, Operand {kind: Literal(a16), immediate: true})}, 
      Opcode {code: 0xCD, name: "CALL", bytes: 3, cycles: 24, immediate: true, operands: vec!(Operand {kind: Literal(a16), immediate: true})}, 
      Opcode {code: 0xCE, name: "ADC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0xCF, name: "RST", bytes: 1, cycles: 16, immediate: true, operands: vec!(Operand {kind: Interrupt(0x08), immediate: true})}, 
      Opcode {code: 0xD0, name: "RET", bytes: 1, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(NC), immediate: true})}, 
      Opcode {code: 0xD1, name: "POP", bytes: 1, cycles: 12, immediate: true, operands: vec!(Operand {kind: Register(DE), immediate: true})}, 
      Opcode {code: 0xD2, name: "JP", bytes: 3, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(NC), immediate: true}, Operand {kind: Literal(a16), immediate: true})}, 
      Opcode {code: 0xD3, name: "ILLEGAL_D3", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xD4, name: "CALL", bytes: 3, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(NC), immediate: true}, Operand {kind: Literal(a16), immediate: true})}, 
      Opcode {code: 0xD5, name: "PUSH", bytes: 1, cycles: 16, immediate: true, operands: vec!(Operand {kind: Register(DE), immediate: true})}, 
      Opcode {code: 0xD6, name: "SUB", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0xD7, name: "RST", bytes: 1, cycles: 16, immediate: true, operands: vec!(Operand {kind: Interrupt(0x10), immediate: true})}, 
      Opcode {code: 0xD8, name: "RET", bytes: 1, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(CY), immediate: true})}, 
      Opcode {code: 0xD9, name: "RETI", bytes: 1, cycles: 16, immediate: true, operands: vec!()}, 
      Opcode {code: 0xDA, name: "JP", bytes: 3, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(CY), immediate: true}, Operand {kind: Literal(a16), immediate: true})}, 
      Opcode {code: 0xDB, name: "ILLEGAL_DB", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xDC, name: "CALL", bytes: 3, cycles: 0, immediate: true, operands: vec!(Operand {kind: Condition(CY), immediate: true}, Operand {kind: Literal(a16), immediate: true})}, 
      Opcode {code: 0xDD, name: "ILLEGAL_DD", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xDE, name: "SBC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0xDF, name: "RST", bytes: 1, cycles: 16, immediate: true, operands: vec!(Operand {kind: Interrupt(0x18), immediate: true})}, 
      Opcode {code: 0xE0, name: "LDH", bytes: 2, cycles: 12, immediate: false, operands: vec!(Operand {kind: Literal(a8), immediate: false}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xE1, name: "POP", bytes: 1, cycles: 12, immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true})}, 
      Opcode {code: 0xE2, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(C), immediate: false}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xE3, name: "ILLEGAL_E3", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xE4, name: "ILLEGAL_E4", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xE5, name: "PUSH", bytes: 1, cycles: 16, immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true})}, 
      Opcode {code: 0xE6, name: "AND", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0xE7, name: "RST", bytes: 1, cycles: 16, immediate: true, operands: vec!(Operand {kind: Interrupt(0x20), immediate: true})}, 
      Opcode {code: 0xE8, name: "ADD", bytes: 2, cycles: 16, immediate: true, operands: vec!(Operand {kind: Register(SP), immediate: true}, Operand {kind: Literal(e8), immediate: true})}, 
      Opcode {code: 0xE9, name: "JP", bytes: 1, cycles: 4, immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true})}, 
      Opcode {code: 0xEA, name: "LD", bytes: 3, cycles: 16, immediate: false, operands: vec!(Operand {kind: Literal(a16), immediate: false}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xEB, name: "ILLEGAL_EB", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xEC, name: "ILLEGAL_EC", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xED, name: "ILLEGAL_ED", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xEE, name: "XOR", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0xEF, name: "RST", bytes: 1, cycles: 16, immediate: true, operands: vec!(Operand {kind: Interrupt(0x28), immediate: true})}, 
      Opcode {code: 0xF0, name: "LDH", bytes: 2, cycles: 12, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(a8), immediate: false})}, 
      Opcode {code: 0xF1, name: "POP", bytes: 1, cycles: 12, immediate: true, operands: vec!(Operand {kind: Register(AF), immediate: true})}, 
      Opcode {code: 0xF2, name: "LD", bytes: 1, cycles: 8, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: false})}, 
      Opcode {code: 0xF3, name: "DI", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xF4, name: "ILLEGAL_F4", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xF5, name: "PUSH", bytes: 1, cycles: 16, immediate: true, operands: vec!(Operand {kind: Register(AF), immediate: true})}, 
      Opcode {code: 0xF6, name: "OR", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0xF7, name: "RST", bytes: 1, cycles: 16, immediate: true, operands: vec!(Operand {kind: Interrupt(0x30), immediate: true})}, 
      Opcode {code: 0xF8, name: "LD", bytes: 2, cycles: 12, immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true}, Operand {kind: Register(SP), immediate: true}, Operand {kind: Literal(e8), immediate: true})}, 
      Opcode {code: 0xF9, name: "LD", bytes: 1, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(SP), immediate: true}, Operand {kind: Register(HL), immediate: true})}, 
      Opcode {code: 0xFA, name: "LD", bytes: 3, cycles: 16, immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(a16), immediate: false})}, 
      Opcode {code: 0xFB, name: "EI", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xFC, name: "ILLEGAL_FC", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xFD, name: "ILLEGAL_FD", bytes: 1, cycles: 4, immediate: true, operands: vec!()}, 
      Opcode {code: 0xFE, name: "CP", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})}, 
      Opcode {code: 0xFF, name: "RST", bytes: 1, cycles: 16, immediate: true, operands: vec!(Operand {kind: Interrupt(0x38), immediate: true})},
    ];

    vec_to_map(opcodes)
  };

  pub static ref CB_OPTABLE: HashMap<u8, Opcode> = {
    let opcodes = vec![
     Opcode {code: 0x00, name: "RLC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x01, name: "RLC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x02, name: "RLC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x03, name: "RLC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x04, name: "RLC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x05, name: "RLC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x06, name: "RLC", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x07, name: "RLC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x08, name: "RRC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x09, name: "RRC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x0A, name: "RRC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x0B, name: "RRC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x0C, name: "RRC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x0D, name: "RRC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x0E, name: "RRC", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x0F, name: "RRC", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x10, name: "RL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x11, name: "RL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x12, name: "RL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x13, name: "RL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x14, name: "RL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x15, name: "RL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x16, name: "RL", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x17, name: "RL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x18, name: "RR", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x19, name: "RR", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x1A, name: "RR", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x1B, name: "RR", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x1C, name: "RR", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x1D, name: "RR", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x1E, name: "RR", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x1F, name: "RR", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x20, name: "SLA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x21, name: "SLA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x22, name: "SLA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x23, name: "SLA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x24, name: "SLA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x25, name: "SLA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x26, name: "SLA", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x27, name: "SLA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x28, name: "SRA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x29, name: "SRA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x2A, name: "SRA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x2B, name: "SRA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x2C, name: "SRA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x2D, name: "SRA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x2E, name: "SRA", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x2F, name: "SRA", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x30, name: "SWAP", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x31, name: "SWAP", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x32, name: "SWAP", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x33, name: "SWAP", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x34, name: "SWAP", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x35, name: "SWAP", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x36, name: "SWAP", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x37, name: "SWAP", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x38, name: "SRL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x39, name: "SRL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x3A, name: "SRL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x3B, name: "SRL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x3C, name: "SRL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x3D, name: "SRL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x3E, name: "SRL", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x3F, name: "SRL", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x40, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x41, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x42, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x43, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x44, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x45, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x46, name: "BIT", bytes: 2, cycles: 12, immediate: false, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x47, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x48, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x49, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x4A, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x4B, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x4C, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x4D, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x4E, name: "BIT", bytes: 2, cycles: 12, immediate: false, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x4F, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x50, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x51, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x52, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x53, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x54, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x55, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x56, name: "BIT", bytes: 2, cycles: 12, immediate: false, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x57, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x58, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x59, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x5A, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x5B, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x5C, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x5D, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x5E, name: "BIT", bytes: 2, cycles: 12, immediate: false, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x5F, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x60, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x61, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x62, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x63, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x64, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x65, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x66, name: "BIT", bytes: 2, cycles: 12, immediate: false, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x67, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x68, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x69, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x6A, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x6B, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x6C, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x6D, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x6E, name: "BIT", bytes: 2, cycles: 12, immediate: false, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x6F, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x70, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x71, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x72, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x73, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x74, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x75, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x76, name: "BIT", bytes: 2, cycles: 12, immediate: false, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x77, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x78, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x79, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x7A, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x7B, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x7C, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x7D, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x7E, name: "BIT", bytes: 2, cycles: 12, immediate: false, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x7F, name: "BIT", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x80, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x81, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x82, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x83, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x84, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x85, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x86, name: "RES", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x87, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x88, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x89, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x8A, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x8B, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x8C, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x8D, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x8E, name: "RES", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x8F, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x90, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x91, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x92, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x93, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x94, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x95, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x96, name: "RES", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x97, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0x98, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0x99, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0x9A, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0x9B, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0x9C, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0x9D, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0x9E, name: "RES", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0x9F, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xA0, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xA1, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xA2, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xA3, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xA4, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xA5, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xA6, name: "RES", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xA7, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xA8, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xA9, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xAA, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xAB, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xAC, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xAD, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xAE, name: "RES", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xAF, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xB0, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xB1, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xB2, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xB3, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xB4, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xB5, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xB6, name: "RES", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xB7, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xB8, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xB9, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xBA, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xBB, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xBC, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xBD, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xBE, name: "RES", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xBF, name: "RES", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xC0, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xC1, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xC2, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xC3, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xC4, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xC5, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xC6, name: "SET", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xC7, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xC8, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xC9, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xCA, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xCB, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xCC, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xCD, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xCE, name: "SET", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xCF, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xD0, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xD1, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xD2, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xD3, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xD4, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xD5, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xD6, name: "SET", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xD7, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xD8, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xD9, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xDA, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xDB, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xDC, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xDD, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xDE, name: "SET", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xDF, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xE0, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xE1, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xE2, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xE3, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xE4, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xE5, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xE6, name: "SET", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xE7, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xE8, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xE9, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xEA, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xEB, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xEC, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xED, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xEE, name: "SET", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xEF, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xF0, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xF1, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xF2, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xF3, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xF4, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xF5, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xF6, name: "SET", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xF7, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(A), immediate: true})}, 
      Opcode {code: 0xF8, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(B), immediate: true})}, 
      Opcode {code: 0xF9, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(C), immediate: true})}, 
      Opcode {code: 0xFA, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(D), immediate: true})}, 
      Opcode {code: 0xFB, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(E), immediate: true})}, 
      Opcode {code: 0xFC, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(H), immediate: true})}, 
      Opcode {code: 0xFD, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(L), immediate: true})}, 
      Opcode {code: 0xFE, name: "SET", bytes: 2, cycles: 16, immediate: false, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(HL), immediate: false})}, 
      Opcode {code: 0xFF, name: "SET", bytes: 2, cycles: 8, immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(A), immediate: true})}
    ];

    vec_to_map(opcodes)
  };
}
