use lazy_static::lazy_static;
use std::collections::HashMap;
use super::addressing::*;
use super::addressing::OperandType::*;
use super::addressing::ConditionOperand::*;
use super::addressing::RegisterOperand::*;
use super::addressing::LiteralOperand::*;

fn vec_to_map(v: Vec<Opcode>) -> HashMap<u16, Opcode> {
  let mut map = HashMap::new();
  for item in v {
    let key = if item.prefixed { 0xCB00 | item.code as u16 } else { item.code as u16};
    map.insert(key, item);
  }

  map
}

lazy_static! {
  pub static ref OPTABLE: HashMap<u16, Opcode> = {
    let opcodes: Vec<Opcode> = vec![
      Opcode {code: 0x00, prefixed: false, name: "NOP", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0x01, prefixed: false, name: "LD", bytes: 3, cycles: (12, 0), immediate: true, operands: vec!(Operand {kind: Register(BC), immediate: true}, Operand {kind: Literal(n16), immediate: true})},
      Opcode {code: 0x02, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(BC), immediate: false}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x03, prefixed: false, name: "INC", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(BC), immediate: true})},
      Opcode {code: 0x04, prefixed: false, name: "INC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x05, prefixed: false, name: "DEC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x06, prefixed: false, name: "LD", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0x07, prefixed: false, name: "RLCA", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0x08, prefixed: false, name: "LD", bytes: 3, cycles: (20, 0), immediate: false, operands: vec!(Operand {kind: Literal(a16), immediate: false}, Operand {kind: Register(SP), immediate: true})},
      Opcode {code: 0x09, prefixed: false, name: "ADD", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true}, Operand {kind: Register(BC), immediate: true})},
      Opcode {code: 0x0A, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(BC), immediate: false})},
      Opcode {code: 0x0B, prefixed: false, name: "DEC", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(BC), immediate: true})},
      Opcode {code: 0x0C, prefixed: false, name: "INC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x0D, prefixed: false, name: "DEC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x0E, prefixed: false, name: "LD", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0x0F, prefixed: false, name: "RRCA", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0x10, prefixed: false, name: "STOP", bytes: 2, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0x11, prefixed: false, name: "LD", bytes: 3, cycles: (12, 0), immediate: true, operands: vec!(Operand {kind: Register(DE), immediate: true}, Operand {kind: Literal(n16), immediate: true})},
      Opcode {code: 0x12, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(DE), immediate: false}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x13, prefixed: false, name: "INC", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(DE), immediate: true})},
      Opcode {code: 0x14, prefixed: false, name: "INC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x15, prefixed: false, name: "DEC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x16, prefixed: false, name: "LD", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0x17, prefixed: false, name: "RLA", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0x18, prefixed: false, name: "JR", bytes: 2, cycles: (12, 0), immediate: true, operands: vec!(Operand {kind: Literal(e8), immediate: true})},
      Opcode {code: 0x19, prefixed: false, name: "ADD", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true}, Operand {kind: Register(DE), immediate: true})},
      Opcode {code: 0x1A, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(DE), immediate: false})},
      Opcode {code: 0x1B, prefixed: false, name: "DEC", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(DE), immediate: true})},
      Opcode {code: 0x1C, prefixed: false, name: "INC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x1D, prefixed: false, name: "DEC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x1E, prefixed: false, name: "LD", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0x1F, prefixed: false, name: "RRA", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0x20, prefixed: false, name: "JR", bytes: 2, cycles: (12, 8), immediate: true, operands: vec!(Operand {kind: Condition(NZ), immediate: true}, Operand {kind: Literal(e8), immediate: true})},
      Opcode {code: 0x21, prefixed: false, name: "LD", bytes: 3, cycles: (12, 0), immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true}, Operand {kind: Literal(n16), immediate: true})},
      Opcode {code: 0x22, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x23, prefixed: false, name: "INC", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true})},
      Opcode {code: 0x24, prefixed: false, name: "INC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x25, prefixed: false, name: "DEC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x26, prefixed: false, name: "LD", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0x27, prefixed: false, name: "DAA", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0x28, prefixed: false, name: "JR", bytes: 2, cycles: (12, 8), immediate: true, operands: vec!(Operand {kind: Condition(Z), immediate: true}, Operand {kind: Literal(e8), immediate: true})},
      Opcode {code: 0x29, prefixed: false, name: "ADD", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true}, Operand {kind: Register(HL), immediate: true})},
      Opcode {code: 0x2A, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x2B, prefixed: false, name: "DEC", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true})},
      Opcode {code: 0x2C, prefixed: false, name: "INC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x2D, prefixed: false, name: "DEC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x2E, prefixed: false, name: "LD", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0x2F, prefixed: false, name: "CPL", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0x30, prefixed: false, name: "JR", bytes: 2, cycles: (12, 8), immediate: true, operands: vec!(Operand {kind: Condition(NC), immediate: true}, Operand {kind: Literal(e8), immediate: true})},
      Opcode {code: 0x31, prefixed: false, name: "LD", bytes: 3, cycles: (12, 0), immediate: true, operands: vec!(Operand {kind: Register(SP), immediate: true}, Operand {kind: Literal(n16), immediate: true})},
      Opcode {code: 0x32, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x33, prefixed: false, name: "INC", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(SP), immediate: true})},
      Opcode {code: 0x34, prefixed: false, name: "INC", bytes: 1, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x35, prefixed: false, name: "DEC", bytes: 1, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x36, prefixed: false, name: "LD", bytes: 2, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0x37, prefixed: false, name: "SCF", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0x38, prefixed: false, name: "JR", bytes: 2, cycles: (12, 8), immediate: true, operands: vec!(Operand {kind: Condition(CY), immediate: true}, Operand {kind: Literal(e8), immediate: true})},
      Opcode {code: 0x39, prefixed: false, name: "ADD", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true}, Operand {kind: Register(SP), immediate: true})},
      Opcode {code: 0x3A, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x3B, prefixed: false, name: "DEC", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(SP), immediate: true})},
      Opcode {code: 0x3C, prefixed: false, name: "INC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x3D, prefixed: false, name: "DEC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x3E, prefixed: false, name: "LD", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0x3F, prefixed: false, name: "CCF", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0x40, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x41, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x42, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x43, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x44, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x45, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x46, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x47, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x48, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x49, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x4A, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x4B, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x4C, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x4D, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x4E, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x4F, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x50, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x51, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x52, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x53, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x54, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x55, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x56, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x57, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x58, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x59, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x5A, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x5B, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x5C, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x5D, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x5E, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x5F, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x60, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x61, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x62, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x63, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x64, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x65, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x66, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x67, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x68, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x69, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x6A, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x6B, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x6C, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x6D, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x6E, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x6F, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x70, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x71, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x72, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x73, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x74, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x75, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x76, prefixed: false, name: "HALT", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0x77, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x78, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x79, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x7A, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x7B, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x7C, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x7D, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x7E, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x7F, prefixed: false, name: "LD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x80, prefixed: false, name: "ADD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x81, prefixed: false, name: "ADD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x82, prefixed: false, name: "ADD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x83, prefixed: false, name: "ADD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x84, prefixed: false, name: "ADD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x85, prefixed: false, name: "ADD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x86, prefixed: false, name: "ADD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x87, prefixed: false, name: "ADD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x88, prefixed: false, name: "ADC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x89, prefixed: false, name: "ADC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x8A, prefixed: false, name: "ADC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x8B, prefixed: false, name: "ADC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x8C, prefixed: false, name: "ADC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x8D, prefixed: false, name: "ADC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x8E, prefixed: false, name: "ADC", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x8F, prefixed: false, name: "ADC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x90, prefixed: false, name: "SUB", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x91, prefixed: false, name: "SUB", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x92, prefixed: false, name: "SUB", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x93, prefixed: false, name: "SUB", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x94, prefixed: false, name: "SUB", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x95, prefixed: false, name: "SUB", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x96, prefixed: false, name: "SUB", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x97, prefixed: false, name: "SUB", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x98, prefixed: false, name: "SBC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x99, prefixed: false, name: "SBC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x9A, prefixed: false, name: "SBC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x9B, prefixed: false, name: "SBC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x9C, prefixed: false, name: "SBC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x9D, prefixed: false, name: "SBC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x9E, prefixed: false, name: "SBC", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x9F, prefixed: false, name: "SBC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xA0, prefixed: false, name: "AND", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xA1, prefixed: false, name: "AND", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xA2, prefixed: false, name: "AND", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xA3, prefixed: false, name: "AND", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xA4, prefixed: false, name: "AND", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xA5, prefixed: false, name: "AND", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xA6, prefixed: false, name: "AND", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xA7, prefixed: false, name: "AND", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xA8, prefixed: false, name: "XOR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xA9, prefixed: false, name: "XOR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xAA, prefixed: false, name: "XOR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xAB, prefixed: false, name: "XOR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xAC, prefixed: false, name: "XOR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xAD, prefixed: false, name: "XOR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xAE, prefixed: false, name: "XOR", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xAF, prefixed: false, name: "XOR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xB0, prefixed: false, name: "OR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xB1, prefixed: false, name: "OR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xB2, prefixed: false, name: "OR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xB3, prefixed: false, name: "OR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xB4, prefixed: false, name: "OR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xB5, prefixed: false, name: "OR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xB6, prefixed: false, name: "OR", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xB7, prefixed: false, name: "OR", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xB8, prefixed: false, name: "CP", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xB9, prefixed: false, name: "CP", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xBA, prefixed: false, name: "CP", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xBB, prefixed: false, name: "CP", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xBC, prefixed: false, name: "CP", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xBD, prefixed: false, name: "CP", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xBE, prefixed: false, name: "CP", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xBF, prefixed: false, name: "CP", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xC0, prefixed: false, name: "RET", bytes: 1, cycles: (20, 8), immediate: true, operands: vec!(Operand {kind: Condition(NZ), immediate: true})},
      Opcode {code: 0xC1, prefixed: false, name: "POP", bytes: 1, cycles: (12, 0), immediate: true, operands: vec!(Operand {kind: Register(BC), immediate: true})},
      Opcode {code: 0xC2, prefixed: false, name: "JP", bytes: 3, cycles: (16, 12), immediate: true, operands: vec!(Operand {kind: Condition(NZ), immediate: true}, Operand {kind: Literal(a16), immediate: true})},
      Opcode {code: 0xC3, prefixed: false, name: "JP", bytes: 3, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Literal(a16), immediate: true})},
      Opcode {code: 0xC4, prefixed: false, name: "CALL", bytes: 3, cycles: (24, 12), immediate: true, operands: vec!(Operand {kind: Condition(NZ), immediate: true}, Operand {kind: Literal(a16), immediate: true})},
      Opcode {code: 0xC5, prefixed: false, name: "PUSH", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Register(BC), immediate: true})},
      Opcode {code: 0xC6, prefixed: false, name: "ADD", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0xC7, prefixed: false, name: "RST", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Interrupt(0x00), immediate: true})},
      Opcode {code: 0xC8, prefixed: false, name: "RET", bytes: 1, cycles: (20, 8), immediate: true, operands: vec!(Operand {kind: Condition(Z), immediate: true})},
      Opcode {code: 0xC9, prefixed: false, name: "RET", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xCA, prefixed: false, name: "JP", bytes: 3, cycles: (16, 12), immediate: true, operands: vec!(Operand {kind: Condition(Z), immediate: true}, Operand {kind: Literal(a16), immediate: true})},
      Opcode {code: 0xCB, prefixed: false, name: "PREFIX", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xCC, prefixed: false, name: "CALL", bytes: 3, cycles: (24, 12), immediate: true, operands: vec!(Operand {kind: Condition(Z), immediate: true}, Operand {kind: Literal(a16), immediate: true})},
      Opcode {code: 0xCD, prefixed: false, name: "CALL", bytes: 3, cycles: (24, 0), immediate: true, operands: vec!(Operand {kind: Literal(a16), immediate: true})},
      Opcode {code: 0xCE, prefixed: false, name: "ADC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0xCF, prefixed: false, name: "RST", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Interrupt(0x08), immediate: true})},
      Opcode {code: 0xD0, prefixed: false, name: "RET", bytes: 1, cycles: (20, 8), immediate: true, operands: vec!(Operand {kind: Condition(NC), immediate: true})},
      Opcode {code: 0xD1, prefixed: false, name: "POP", bytes: 1, cycles: (12, 0), immediate: true, operands: vec!(Operand {kind: Register(DE), immediate: true})},
      Opcode {code: 0xD2, prefixed: false, name: "JP", bytes: 3, cycles: (16, 12), immediate: true, operands: vec!(Operand {kind: Condition(NC), immediate: true}, Operand {kind: Literal(a16), immediate: true})},
      Opcode {code: 0xD3, prefixed: false, name: "ILLEGAL_D3", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xD4, prefixed: false, name: "CALL", bytes: 3, cycles: (24, 12), immediate: true, operands: vec!(Operand {kind: Condition(NC), immediate: true}, Operand {kind: Literal(a16), immediate: true})},
      Opcode {code: 0xD5, prefixed: false, name: "PUSH", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Register(DE), immediate: true})},
      Opcode {code: 0xD6, prefixed: false, name: "SUB", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0xD7, prefixed: false, name: "RST", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Interrupt(0x10), immediate: true})},
      Opcode {code: 0xD8, prefixed: false, name: "RET", bytes: 1, cycles: (20, 8), immediate: true, operands: vec!(Operand {kind: Condition(CY), immediate: true})},
      Opcode {code: 0xD9, prefixed: false, name: "RETI", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xDA, prefixed: false, name: "JP", bytes: 3, cycles: (16, 12), immediate: true, operands: vec!(Operand {kind: Condition(CY), immediate: true}, Operand {kind: Literal(a16), immediate: true})},
      Opcode {code: 0xDB, prefixed: false, name: "ILLEGAL_DB", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xDC, prefixed: false, name: "CALL", bytes: 3, cycles: (24, 12), immediate: true, operands: vec!(Operand {kind: Condition(CY), immediate: true}, Operand {kind: Literal(a16), immediate: true})},
      Opcode {code: 0xDD, prefixed: false, name: "ILLEGAL_DD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xDE, prefixed: false, name: "SBC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0xDF, prefixed: false, name: "RST", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Interrupt(0x18), immediate: true})},
      Opcode {code: 0xE0, prefixed: false, name: "LDH", bytes: 2, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Literal(a8), immediate: false}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xE1, prefixed: false, name: "POP", bytes: 1, cycles: (12, 0), immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true})},
      Opcode {code: 0xE2, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(C), immediate: false}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xE3, prefixed: false, name: "ILLEGAL_E3", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xE4, prefixed: false, name: "ILLEGAL_E4", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xE5, prefixed: false, name: "PUSH", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true})},
      Opcode {code: 0xE6, prefixed: false, name: "AND", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0xE7, prefixed: false, name: "RST", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Interrupt(0x20), immediate: true})},
      Opcode {code: 0xE8, prefixed: false, name: "ADD", bytes: 2, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Register(SP), immediate: true}, Operand {kind: Literal(e8), immediate: true})},
      Opcode {code: 0xE9, prefixed: false, name: "JP", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true})},
      Opcode {code: 0xEA, prefixed: false, name: "LD", bytes: 3, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Literal(a16), immediate: false}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xEB, prefixed: false, name: "ILLEGAL_EB", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xEC, prefixed: false, name: "ILLEGAL_EC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xED, prefixed: false, name: "ILLEGAL_ED", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xEE, prefixed: false, name: "XOR", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0xEF, prefixed: false, name: "RST", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Interrupt(0x28), immediate: true})},
      Opcode {code: 0xF0, prefixed: false, name: "LDH", bytes: 2, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(a8), immediate: false})},
      Opcode {code: 0xF1, prefixed: false, name: "POP", bytes: 1, cycles: (12, 0), immediate: true, operands: vec!(Operand {kind: Register(AF), immediate: true})},
      Opcode {code: 0xF2, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Register(C), immediate: false})},
      Opcode {code: 0xF3, prefixed: false, name: "DI", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xF4, prefixed: false, name: "ILLEGAL_F4", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xF5, prefixed: false, name: "PUSH", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Register(AF), immediate: true})},
      Opcode {code: 0xF6, prefixed: false, name: "OR", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0xF7, prefixed: false, name: "RST", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Interrupt(0x30), immediate: true})},
      Opcode {code: 0xF8, prefixed: false, name: "LD", bytes: 2, cycles: (12, 0), immediate: true, operands: vec!(Operand {kind: Register(HL), immediate: true}, Operand {kind: Register(SP), immediate: true}, Operand {kind: Literal(e8), immediate: true})},
      Opcode {code: 0xF9, prefixed: false, name: "LD", bytes: 1, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(SP), immediate: true}, Operand {kind: Register(HL), immediate: true})},
      Opcode {code: 0xFA, prefixed: false, name: "LD", bytes: 3, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(a16), immediate: false})},
      Opcode {code: 0xFB, prefixed: false, name: "EI", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xFC, prefixed: false, name: "ILLEGAL_FC", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xFD, prefixed: false, name: "ILLEGAL_FD", bytes: 1, cycles: (4, 0), immediate: true, operands: vec!()},
      Opcode {code: 0xFE, prefixed: false, name: "CP", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true}, Operand {kind: Literal(n8), immediate: true})},
      Opcode {code: 0xFF, prefixed: false, name: "RST", bytes: 1, cycles: (16, 0), immediate: true, operands: vec!(Operand {kind: Interrupt(0x38), immediate: true})},

      Opcode {code: 0x00, prefixed: true, name: "RLC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x01, prefixed: true, name: "RLC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x02, prefixed: true, name: "RLC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x03, prefixed: true, name: "RLC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x04, prefixed: true, name: "RLC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x05, prefixed: true, name: "RLC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x06, prefixed: true, name: "RLC", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x07, prefixed: true, name: "RLC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x08, prefixed: true, name: "RRC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x09, prefixed: true, name: "RRC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x0A, prefixed: true, name: "RRC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x0B, prefixed: true, name: "RRC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x0C, prefixed: true, name: "RRC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x0D, prefixed: true, name: "RRC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x0E, prefixed: true, name: "RRC", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x0F, prefixed: true, name: "RRC", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x10, prefixed: true, name: "RL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x11, prefixed: true, name: "RL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x12, prefixed: true, name: "RL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x13, prefixed: true, name: "RL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x14, prefixed: true, name: "RL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x15, prefixed: true, name: "RL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x16, prefixed: true, name: "RL", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x17, prefixed: true, name: "RL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x18, prefixed: true, name: "RR", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x19, prefixed: true, name: "RR", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x1A, prefixed: true, name: "RR", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x1B, prefixed: true, name: "RR", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x1C, prefixed: true, name: "RR", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x1D, prefixed: true, name: "RR", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x1E, prefixed: true, name: "RR", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x1F, prefixed: true, name: "RR", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x20, prefixed: true, name: "SLA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x21, prefixed: true, name: "SLA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x22, prefixed: true, name: "SLA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x23, prefixed: true, name: "SLA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x24, prefixed: true, name: "SLA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x25, prefixed: true, name: "SLA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x26, prefixed: true, name: "SLA", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x27, prefixed: true, name: "SLA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x28, prefixed: true, name: "SRA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x29, prefixed: true, name: "SRA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x2A, prefixed: true, name: "SRA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x2B, prefixed: true, name: "SRA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x2C, prefixed: true, name: "SRA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x2D, prefixed: true, name: "SRA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x2E, prefixed: true, name: "SRA", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x2F, prefixed: true, name: "SRA", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x30, prefixed: true, name: "SWAP", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x31, prefixed: true, name: "SWAP", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x32, prefixed: true, name: "SWAP", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x33, prefixed: true, name: "SWAP", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x34, prefixed: true, name: "SWAP", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x35, prefixed: true, name: "SWAP", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x36, prefixed: true, name: "SWAP", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x37, prefixed: true, name: "SWAP", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x38, prefixed: true, name: "SRL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x39, prefixed: true, name: "SRL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x3A, prefixed: true, name: "SRL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x3B, prefixed: true, name: "SRL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x3C, prefixed: true, name: "SRL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x3D, prefixed: true, name: "SRL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x3E, prefixed: true, name: "SRL", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x3F, prefixed: true, name: "SRL", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x40, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x41, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x42, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x43, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x44, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x45, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x46, prefixed: true, name: "BIT", bytes: 2, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x47, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x48, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x49, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x4A, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x4B, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x4C, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x4D, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x4E, prefixed: true, name: "BIT", bytes: 2, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x4F, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x50, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x51, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x52, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x53, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x54, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x55, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x56, prefixed: true, name: "BIT", bytes: 2, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x57, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x58, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x59, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x5A, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x5B, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x5C, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x5D, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x5E, prefixed: true, name: "BIT", bytes: 2, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x5F, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x60, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x61, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x62, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x63, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x64, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x65, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x66, prefixed: true, name: "BIT", bytes: 2, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x67, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x68, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x69, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x6A, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x6B, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x6C, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x6D, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x6E, prefixed: true, name: "BIT", bytes: 2, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x6F, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x70, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x71, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x72, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x73, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x74, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x75, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x76, prefixed: true, name: "BIT", bytes: 2, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x77, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x78, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x79, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x7A, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x7B, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x7C, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x7D, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x7E, prefixed: true, name: "BIT", bytes: 2, cycles: (12, 0), immediate: false, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x7F, prefixed: true, name: "BIT", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x80, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x81, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x82, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x83, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x84, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x85, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x86, prefixed: true, name: "RES", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x87, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x88, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x89, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x8A, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x8B, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x8C, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x8D, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x8E, prefixed: true, name: "RES", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x8F, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x90, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x91, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x92, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x93, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x94, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x95, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x96, prefixed: true, name: "RES", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x97, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0x98, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0x99, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0x9A, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0x9B, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0x9C, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0x9D, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0x9E, prefixed: true, name: "RES", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0x9F, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xA0, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xA1, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xA2, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xA3, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xA4, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xA5, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xA6, prefixed: true, name: "RES", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xA7, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xA8, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xA9, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xAA, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xAB, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xAC, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xAD, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xAE, prefixed: true, name: "RES", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xAF, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xB0, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xB1, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xB2, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xB3, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xB4, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xB5, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xB6, prefixed: true, name: "RES", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xB7, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xB8, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xB9, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xBA, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xBB, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xBC, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xBD, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xBE, prefixed: true, name: "RES", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xBF, prefixed: true, name: "RES", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xC0, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xC1, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xC2, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xC3, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xC4, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xC5, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xC6, prefixed: true, name: "SET", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xC7, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(0), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xC8, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xC9, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xCA, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xCB, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xCC, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xCD, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xCE, prefixed: true, name: "SET", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xCF, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(1), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xD0, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xD1, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xD2, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xD3, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xD4, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xD5, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xD6, prefixed: true, name: "SET", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xD7, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(2), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xD8, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xD9, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xDA, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xDB, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xDC, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xDD, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xDE, prefixed: true, name: "SET", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xDF, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(3), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xE0, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xE1, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xE2, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xE3, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xE4, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xE5, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xE6, prefixed: true, name: "SET", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xE7, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(4), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xE8, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xE9, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xEA, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xEB, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xEC, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xED, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xEE, prefixed: true, name: "SET", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xEF, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(5), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xF0, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xF1, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xF2, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xF3, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xF4, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xF5, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xF6, prefixed: true, name: "SET", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xF7, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(6), immediate: true}, Operand {kind: Register(A), immediate: true})},
      Opcode {code: 0xF8, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(B), immediate: true})},
      Opcode {code: 0xF9, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(C), immediate: true})},
      Opcode {code: 0xFA, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(D), immediate: true})},
      Opcode {code: 0xFB, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(E), immediate: true})},
      Opcode {code: 0xFC, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(H), immediate: true})},
      Opcode {code: 0xFD, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(L), immediate: true})},
      Opcode {code: 0xFE, prefixed: true, name: "SET", bytes: 2, cycles: (16, 0), immediate: false, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(HL), immediate: false})},
      Opcode {code: 0xFF, prefixed: true, name: "SET", bytes: 2, cycles: (8, 0), immediate: true, operands: vec!(Operand {kind: Bit(7), immediate: true}, Operand {kind: Register(A), immediate: true})}
    ];

    vec_to_map(opcodes)
  };
}
